### ISSUE TITLE
Collection order

### ISSUE THREAD

**Issue by reinij** [nlsfi/hakunapi#128]
Modify collection order to follow the collection list in the properties file. Now it seems to be random at least with Geopackage as a data source.

An example:
`collections=aita, allas, ankkuripaikka, autoliikennealue, avoin_metsamaa, building_installation, eramaa_alue, erityisalue, esterakennelma, harva_louhikko,...`

and in HTML
![image](https://github.com/user-attachments/assets/4117d1fc-6d93-4b1d-a459-f096bbe56e10)

**Comment by jampukka** [comment]
This is due to `FeatureServiceConfig #getCollections` returning the values from a `HashMap` where the order is not "random" (it doesn't change per request) but it's not alphabetic or the insertion order either. Fixing this is very easy.

I'm assuming the expected order would the one in that appears in configuration (and not alphabetical), e.g.
`collections=z, x, y`
Would return 
* Z
* X
* Y

**Comment by reinij** [comment]
This sounds as a reasonable fix.
