### ISSUE TITLE
Support for containerized deployment and cloud service hosting

### ISSUE THREAD

**Issue by teezip** [nlsfi/hakunapi#50]
Support and documentation for:

* deployment as a Docker container (actions, hakunapi-simple-webapp bundled as a container, etc)
* hakunapi-simple-webapp published in a container register (GitHub, Docker or Azure)
* example app (https://github.com/nlsfi/hakunapi/tree/main/examples/finnish_addresses) also as a container with instructions  
* example app container deployed to a cloud service (ie. Azure App Service) to host a demo service 

Currently the finnish_addresses example is available online (https://beta-paikkatieto.maanmittauslaitos.fi/inspire-addresses/features/v1/) without access restriction, but not in a managed cloud service.

**Comment by tsallinen** [comment]
Some enhancements should be made to Hakunapi in order to enable PAAS or containerized deployment:

- [ ] Support configuring database connection settings as environment variables (as an alternative to db.properties)
- [ ] Optionally support Azure managed identity for database authentication (instead of username/password). See https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/connect-java?tabs=passwordless
- [ ] Support environment variables as an alternative to any system properties ({context_path}.hakuna.config.path)
- [ ] Construct links dynamically from request headers (Host, X-Forwarded-*) instead of static configuration (servers.dev.url)

**Comment by jampukka** [comment]
If I understand the [passwordless example](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/connect-java?tabs=passwordless) correctly users should now be able to create their own version of `hakunapi-simple-webapp-javax` and include the
```
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-identity-extensions</artifactId>
  <version>1.0.0</version>
</dependency>
```
in the war project and configure their database connections with `jdbcUrl` instead of `dataSourceClassName` [causing HikariCP](https://github.com/brettwooldridge/HikariCP#essentials) to call `DriverManager.getConnection(jdbcUrl, props)` [just like the example code does](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/connect-java?tabs=passwordless#connect-to-the-database)

Current example configuration:
```
dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
dataSource.user=address_reader
dataSource.password=test
dataSource.databaseName=address_fin
dataSource.portNumber=5432
dataSource.serverName=localhost
```

How it could work:
```
jdbcUrl=jdbc:postgresql://${AZ_DATABASE_SERVER_NAME}.postgres.database.azure.com:5432/${AZ_DATABASE_NAME}?sslmode=require&authenticationPluginClassName=com.azure.identity.extensions.jdbc.postgresql.AzurePostgresqlAuthenticationPlugin
dataSource.user=address_reader
```

**Comment by jampukka** [comment]
Quick test, adding
```
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-identity-extensions</artifactId>
  <version>1.0.0</version>
</dependency>
```
to `hakunapi-source-postgis` causes `features.war` to grow from 33mb to 51mb. Might not be an issue, but not the tiniest dependency to add

**Comment by jampukka** [comment]
@tsallinen, did this
- [ ] Optionally support Azure managed identity for database authentication (instead of username/password). See https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/connect-java?tabs=passwordless

also get completed?

**Comment by tsallinen** [comment]
I am unable to verify that for now, but I think we can close this issue and open a new one later if further changes are needed. Hakunapi is now ready for containers.

**Comment by teezip** [comment]
As commented above "we can close this issue and open a new one later if further changes are needed".
